spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  data:
    mongodb:
      uri:
app:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMsec: 864000000
  authorizedRedirectUris: 
  - http://localhost:3000/oauth2/redirect
